kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replica: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: vikashashoke/mydemoapplication:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9099
